-- Sessions table: tracks WhatsApp device sessions managed by the API.
create table if not exists public.sessions (
    id              bigserial primary key,
    serial          uuid not null default gen_random_uuid(),
    phone_number_id text not null unique,
    number          text not null,
    display_phone   text not null default '',
    status          text not null default 'created'
                    check (status in ('created', 'pairing', 'connected', 'disconnected', 'logged_out')),
    whatsapp_id     text,
    connected_at    timestamptz,
    last_seen_at    timestamptz,
    logged_out_at   timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now(),
    deleted_at      timestamptz
);

create unique index if not exists sessions_serial_idx
    on public.sessions (serial);

create trigger sessions_set_updated_at
    before update on public.sessions
    for each row execute function public.set_updated_at();

-- Session QR codes: temporary storage for QR payloads generated by the worker.
-- Each pairing attempt produces one row; expired rows can be cleaned up.
create table if not exists public.session_qr_codes (
    id              bigserial primary key,
    serial          uuid not null default gen_random_uuid(),
    session_id      bigint not null references public.sessions(id) on delete cascade,
    phone_number_id text not null,
    qr_code         text not null,
    status          text not null default 'pending'
                    check (status in ('pending', 'ready', 'expired')),
    expires_at      timestamptz not null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

create unique index if not exists session_qr_codes_serial_idx
    on public.session_qr_codes (serial);

create index if not exists session_qr_codes_session_idx
    on public.session_qr_codes (session_id, created_at desc);

create trigger session_qr_codes_set_updated_at
    before update on public.session_qr_codes
    for each row execute function public.set_updated_at();
